name = "mathematical_finance"
description = ""
created = "2026-03-02"
preamble = ""

[[cards]]
id = "8ff8b931-a5c5-4aeb-8aca-f8a1bcf6f06c"
front = "What is the definition of simple interest"
back = """
With principal $P$, annual rate $r$, and time $T$ years:

$ P_T = P(1 + r T) $"""

[[cards]]
id = "a714b190-7a86-419b-9c0a-904d529ba319"
front = "What is the definition of compound interest"
back = "$ P_T = P(1 + r)^T $"
